<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flightID234</name>
   <tag></tag>
   <elementGuidId>175f2e0c-5318-4371-9433-8dea0f59580e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-child(2) td:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'tr') and (position() = 2)]//*[(name() = 'td') and (position() = 3)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;234&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>44c26393-648c-43ef-9107-7bd0c24e9bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>234</value>
      <webElementGuid>849c4121-3eff-4e99-919f-133145c86a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5c136af68fc9036996946a7eec77572c</value>
      <webElementGuid>90e830f7-ea1b-46b5-a722-75a9783ccf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 2)]//*[(name() = 'td') and (position() = 3)]</value>
      <webElementGuid>5789ebef-a738-44e4-b5a3-a1638a021080</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 2)]//*[(name() = 'td') and (position() = 3)]</value>
      <webElementGuid>ae97f25b-d0df-4900-b281-c321bccfb55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '234' or . = '234')]</value>
      <webElementGuid>841e594b-ab7d-4ab8-9600-1d88a627115c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
