<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>month</name>
   <tag></tag>
   <elementGuidId>64300d51-5527-43af-bc6c-62ff57c8b101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCardMonth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'creditCardMonth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Month&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ff4e24f-a9f7-4a50-ac13-74e4d3134af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4096531-9e1e-4a7a-af15-4e899de3d427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCardMonth</value>
      <webElementGuid>dd1dc7b2-4591-49d8-a85a-1d058c9e266a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>creditCardMonth</value>
      <webElementGuid>66184327-ec2c-46ed-85ce-1b48bb0a2c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>47acbd73-6327-446e-b743-cf41e4176ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>98a12b30-ae5f-45db-831d-e33c95db5c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7f2ccedd62e59036b22bf8f41ae2b963</value>
      <webElementGuid>2069c086-58af-44b6-b09c-722064cc9a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'creditCardMonth']</value>
      <webElementGuid>058f765f-ebbe-4b60-82d2-4a56b9cb5904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'creditCardMonth']</value>
      <webElementGuid>82f0b665-b1db-460a-a375-411e2855f332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'creditCardMonth' and @name = 'creditCardMonth' and @placeholder = 'Month']</value>
      <webElementGuid>3dbd9d8a-3600-475c-8617-8926bf78451d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
