<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zipCode</name>
   <tag></tag>
   <elementGuidId>3a502812-0437-4f5b-a598-16c964c3e5f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zipCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'zipCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;12345&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>372d1fc5-fe0d-4cdc-8f36-c814b2e75d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7941487-8ede-454d-bce0-873039cd02fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>e86c5098-69e8-4a3d-a72e-356c91306f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>fe49973e-4f88-4397-8059-26d38c0ee19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>4ff185e6-5fd8-4f0d-abf1-fd3f1a5976f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e7bbafe3b138ba71913b00c414a0cbe9</value>
      <webElementGuid>30089ee7-04c9-454e-8f84-80abc9b97b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'zipCode']</value>
      <webElementGuid>1d0f3b93-7166-48bc-ad19-109114bddaae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'zipCode']</value>
      <webElementGuid>147b47c2-7b8c-407b-a8f4-ad9b24ef0f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'zipCode' and @id = 'zipCode' and @placeholder = '12345']</value>
      <webElementGuid>fb90a22f-9218-46e2-93c9-0f3c2cb14275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
